<?php

namespace mrssoft\formwidgets;

use yii\validators\Validator;

/**
 * Validate phone
 */
class PhoneValidator extends Validator
{
    /**
     * Return length of phone number (default - null, do not crop phone number)
     * @var int
     */
    public $returnLenght = 0;

    /**
     * @var bool
     */
    public $checkNine = true;

    public $message = 'Поле «{attribute}» должно содержать 10 или 11 цифр номера.';

    public $messageNine = 'Неверный формат номера телефона.';

    public function validateAttribute($model, $attribute)
    {
        $result = (string)preg_replace('/\D/', '', $model->{$attribute});
        $lenght = mb_strlen($result);
        if ($lenght < 10 || $lenght > 11) {
            $this->addError($model, $attribute, $this->message);
        }

        if ($this->returnLenght && $lenght != $this->returnLenght) {
            $result = substr($result, $lenght - $this->returnLenght);
            if ($this->checkNine) {
                $pos = $this->returnLenght == 10 ? 0 : 1;
                if (mb_substr($result, $pos, 1) != 9) {
                    $this->addError($model, $attribute, $this->messageNine);
                }
            }
        }

        $model->{$attribute} = $result;
    }

    public function validateValue($value)
    {
        parent::validateValue($value); // TODO: Change the autogenerated stub
    }

    public function clientValidateAttribute($model, $attribute, $view)
    {
        $message = $this->formatMessage($this->message, ['attribute' => $model->getAttributeLabel($attribute)]);
        $message = json_encode($message, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        return "value = value.replace(/\D/g, ''); if (value.length < 10 || value.length > 11) { messages.push($message); }";
    }
}